sudo: false
language:
  - erlang
otp_release:
  - 21.0
  - 20.1
  - 20.0
  - 19.3
  - 19.2
  - 19.1
  - 19.0
  - 18.3
  - 18.2
  - 18.1
  - 18.0
script:
  - "[[ ${TRAVIS_OTP_RELEASE} != 18.2 ]] || make elvis"
  - make
  - make test
