---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [18.0, 18.1, 18.2, 18.3, 19.0, 19.1, 19.2, 19.3, 20.0, 20.1, 20.2, 20.3, 21.1, 21.2, 21.3, 22.0, 22.1, 22.2, 22.3, 23.0, 23.1]
        os: [ubuntu-latest]
    env:
      LATEST_OTP_RELEASE: 23.1
    steps:
      - uses: actions/checkout@v2
      - run: [[ ${{matrix.otp_vsn}} != ${{env.LATEST_OTP_RELEASE}} ]] || make elvis docs
      - run: make
      - run: make test
