---
name: CI
on:
  push:
    branches:
      - github*
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 0 * * *
jobs:
  ci:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        otp_vsn:
          - 18.0
          - 18.1
          - 18.2
          - 18.3
          - 19.0
          - 19.1
          - 19.2
          - 19.3
          - 20.0
          - 20.1
          - 20.2
          - 20.3
          - 21.1
          - 21.2
          - 21.3
          - 22.0
          - 22.1
          - 22.2
          - 22.3
          - 23.0
          - 23.1
    name: 'ci-erl:${{ matrix.otp_vsn }}'
    runs-on: ubuntu-latest
    container:
      image: 'erlang:${{ matrix.otp_vsn }}'
    env:
      LATEST_OTP_RELEASE: 23.1
    steps:
      - shell: bash
        run: |
          # upgrade git to 2.18+ for actions/checkout@v2
          set -euo pipefail
          set -x
          echo "deb http://cloudfront.debian.net/debian stretch-backports main" >>/etc/apt/sources.list
          echo "deb-src http://cloudfront.debian.net/debian stretch-backports main" >>/etc/apt/sources.list
          apt-get update -y -o Acquire::Check-Valid-Until=false
          apt-get -t stretch-backports install -y git
      - uses: actions/checkout@v2
      - shell: bash
        run: '[[ "${{ matrix.otp_vsn }}" != "${{ env.LATEST_OTP_RELEASE }}" ]] || make elvis docs'
      - shell: bash
        run: make
      - shell: bash
        run: make test
