---
name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 0 * * *
jobs:
  ci:
    strategy:
      matrix:
        otp_vsn:
          - 18.0
          - 18.1
          - 18.2
          - 18.3
          - 19.0
          - 19.1
          - 19.2
          - 19.3
          - 20.0
          - 20.1
          - 20.2
          - 20.3
          - 21.1
          - 21.2
          - 21.3
          - 22.0
          - 22.1
          - 22.2
          - 22.3
          - 23.0
          - 23.1
    runs-on: ubuntu-latest
    container:
      image: erlang:${{matrix.otp_vsn}}
    env:
      LATEST_OTP_RELEASE: 23.1
    steps:
      - uses: actions/checkout@v2
      - run: '[[ "${{ matrix.otp_vsn }}" != "${{ env.LATEST_OTP_RELEASE }}" ]] || make elvis docs'
      - run: make
      - run: make test
