---
name: CI
on:
  push:
    branches:
      - github*
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: 0 0 * * *
jobs:
  ci:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        otp_vsn:
          - 18.0
          - 18.1
          - 18.2
          - 18.3
          - 19.0
          - 19.1
          - 19.2
          - 19.3
          - 20.0
          - 20.1
          - 20.2
          - 20.3
          - 21.1
          - 21.2
          - 21.3
          - 22.0
          - 22.1
          - 22.2
          - 22.3
          # - 23.0
          # - 23.1
    name: 'ci-erl:${{ matrix.otp_vsn }}'
    runs-on: ubuntu-latest
    container:
      image: 'erlang:${{ matrix.otp_vsn }}'
    env:
      # LATEST_OTP_RELEASE: 23.1
      LATEST_OTP_RELEASE: 22.3
    steps:
      - shell: bash
        run: |
          # upgrade git to 2.18+ for actions/checkout@v2
          # NOTE can't use backports; see git history
          # NOTE skipping the contrib; see git history
          set -euo pipefail
          set -x
          apt-get update -y --fix-missing -o Acquire::Check-Valid-Until=false
          apt-get upgrade -y
          apt-get install -y make libssl-dev libghc-zlib-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip
          cd /usr/src/
          wget https://github.com/git/git/archive/v2.18.0.tar.gz -O git.tar.gz
          tar -xzf git.tar.gz
          cd git-*
          make prefix=/usr/local all
          make prefix=/usr/local install
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          # run linter and docs if latest otp release
          [[ "${{ matrix.otp_vsn }}" != "${{ env.LATEST_OTP_RELEASE }}" ]] || make elvis docs
      - shell: bash
        run: make
      - shell: bash
        run: make test
